### ISSUE TITLE
Design review v21

### ISSUE THREAD

**Issue by lewispg228** [sparkfun/LilyPad_Arduino_328_Main_Board#1]
1) Remove strange GND polygon under reset button

2) Needs a note about proper VCC range in schematic, and possibly a note about must match which FTDI VCC you are using (3.3V or 5V)

3) Route resonator trace off "upper" pad so that it goes outward, and avoids causing a "T" underneath the part.

4) Needs version number in copper

5) Remove "FEMALE 2X3" value on JP3

6) Better placement of name/value on U1 (in schematic)

7) Move vias on FTDI header pads off of the pads, re-route as necessary

8) Increase trace width on GND and VCC to 16 mil.

9) Our new standard for Stat LEDs is Blue, but this could be an exception if it is deemed to much of a pain point to update documentation.

10) Use GND/VCC symbols coming off of JP1.

11) include measures on layer 47 (maybe just the diameter)

12) Needs fiducials

13) I think it would be worth adding a bottom side trace from the "-" pedal to the ground pour to increase the amount of copper connecting to GND. As it is now, there is really only a single 12 mil trace returning all current form the board to GND.

14) Needs note on tdocu about special board thickness

15) add "stat" silk for  stat LED. Maybe lilypad is an exception?

16) Label the reset button with some silk

**Comment by RobotGirlfriend** [comment]
1) Done
2) Done
3) Done
4) Done
5) Done
6) Done
7) These were always here (I moved them up the pad a bit, but didn't add them), and probably helping to root down a connector that's likely to get significant stress. Is removing them worth it/necessary?
8) Done
9) EDU doesn't care if we change it, so I'm running it by Leah.
10) Done
11) Done
12) Done
13) Done
14) Done
15) I've added a label, but the LED doesn't actually reflect any 'status' of the board, so I've labeled it "13". It's tied to pin 13 and that's what most educational materials use it for.
16) Done

**Comment by RobotGirlfriend** [comment]
Update: Leah has no problem changing the LED to blue, so I went ahead and did that. Also added sparkfun flame and OSHW logo in the copper.

**Comment by lewispg228** [comment]
Looks good. thanks!

Two things:

1) we normally put info notes in the schematic on the info layer - you currently have a not on the nets layer.

2) the note about the board thickness is usually in mm and include the color too so "purple 0.08mm"

**Comment by RobotGirlfriend** [comment]
Thank you! Fixed! I'll make sure to apply these changes to the tilt and
reed switch boards as well!

  <3 <3 <3

Dia Campbell
Techstyle Specialist
Sparkfun Electronics
303.284.0979 x407

**Comment by lewispg228** [comment]
Looks good thanks. 

My vote would be to remove the "G" and "B" labeling the FTDI header, but if you or leah or someone else really wants them there, then I guess it's fine.

**Comment by RobotGirlfriend** [comment]
I was originally advised to add BLK and GRN, then noticed that it was
previously just B and G. If what you're saying is that it's okay to remove
the silk there entirely, I'd love to!

  <3 <3 <3

Dia Campbell
Techstyle Specialist
Sparkfun Electronics
303.284.0979 x407

**Comment by lewispg228** [comment]
Please check in with EDU and CS. If either of them wants them there, then lets keep them.
