### ISSUE TITLE
Do you know if there will be a "Genuino" version of this board?

### ISSUE THREAD

**Issue by q2dg** [sparkfun/LilyPad_Arduino_328_Main_Board#2]
I fear for the future of this board (in terms of distribution and, as a consequenca, of production).
Thanks!

**Comment by mshorter** [comment]
Right now this board is produced by Sparkfun and we are staying out of the Arduino war (feels too much like mommy and daddy fighting and the kids being the ones to suffer).  If there comes a point where it is no longer legal for us to sell "Arduino" boards we will most likely just take Arduino out of the name.  Trying to produce 2 versions of a board is not something we really want to do.

**Comment by q2dg** [comment]
Ok, perfectly understood. I'll close this issue, then
